// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtyoGKVWnEPqdjxKoGBegYfKiep73BlAM',
    appId: '1:1080298939557:web:d1b6c67c4ed6a8b95f594c',
    messagingSenderId: '1080298939557',
    projectId: 'suvidha2-35327',
    authDomain: 'suvidha2-35327.firebaseapp.com',
    storageBucket: 'suvidha2-35327.firebasestorage.app',
    measurementId: 'G-QLDDM41NRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8a8pMiUknlDcLFm0YR_s-IY4hJ4-KmLU',
    appId: '1:1080298939557:android:07a4c2143fa6d8525f594c',
    messagingSenderId: '1080298939557',
    projectId: 'suvidha2-35327',
    storageBucket: 'suvidha2-35327.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3lUhPPi6gBLcN957hic_vyBzM00kiG6o',
    appId: '1:1080298939557:ios:6a799054ad61c3225f594c',
    messagingSenderId: '1080298939557',
    projectId: 'suvidha2-35327',
    storageBucket: 'suvidha2-35327.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3lUhPPi6gBLcN957hic_vyBzM00kiG6o',
    appId: '1:1080298939557:ios:6a799054ad61c3225f594c',
    messagingSenderId: '1080298939557',
    projectId: 'suvidha2-35327',
    storageBucket: 'suvidha2-35327.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtyoGKVWnEPqdjxKoGBegYfKiep73BlAM',
    appId: '1:1080298939557:web:09fd882b227860355f594c',
    messagingSenderId: '1080298939557',
    projectId: 'suvidha2-35327',
    authDomain: 'suvidha2-35327.firebaseapp.com',
    storageBucket: 'suvidha2-35327.firebasestorage.app',
    measurementId: 'G-NGRFZ1EFXJ',
  );
}
